spring.application.name=gestion-incidencias

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_incidencias
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080